# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: Nexys4DDR_Master.xdc

# Block Designs: bd/TBA_Block/TBA_Block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TBA_Block || ORIG_REF_NAME==TBA_Block} -quiet] -quiet

# IP: bd/TBA_Block/ip/TBA_Block_HA_source_0_0/TBA_Block_HA_source_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TBA_Block_HA_source_0_0 || ORIG_REF_NAME==TBA_Block_HA_source_0_0} -quiet] -quiet

# XDC: c:/Users/bhumm/OneDrive - TalTech/IAS0600_VHDL/project_3_2BitAdder/project_3_2BitAdder.gen/sources_1/bd/TBA_Block/TBA_Block_ooc.xdc
