# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab 2 Source files/Nexys4DDR_Master.xdc

# Block Designs: bd/TBA_Block/TBA_Block.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TBA_Block || ORIG_REF_NAME==TBA_Block} -quiet] -quiet

# IP: bd/TBA_Block/ip/TBA_Block_HA_source_0_0/TBA_Block_HA_source_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TBA_Block_HA_source_0_0 || ORIG_REF_NAME==TBA_Block_HA_source_0_0} -quiet] -quiet

# IP: bd/TBA_Block/ip/TBA_Block_FA_Source_0_0/TBA_Block_FA_Source_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TBA_Block_FA_Source_0_0 || ORIG_REF_NAME==TBA_Block_FA_Source_0_0} -quiet] -quiet

# XDC: bd/TBA_Block/TBA_Block_ooc.xdc
